### PR TITLE
Make Goerli work again

### PR DESCRIPTION
**Pull request by manuelwedler**
This PR makes the new wizard usable on goerli testnet. It adds an selector on the first page to let the user choose to use Mainnet or Goerli.

### CODE REVIEW

**Comment by fredo** [comment]
Here is the code which we could get rid of with your pending transaction nonce change

https://github.com/raiden-network/raiden-wizard/blob/a0b60f7c1e660b6a3b06526b737f8fabc020746b/raiden_installer/transactions.py#L67

**Comment by manuelwedler** [comment]
I'll add a commit for this change!

**Comment by fredo** [comment]
How complex would it be to change the Service Token Ticker to "SVT" when being on goerli? It is currently called `RDN`. To be copmpliant with the naming of the [actual contract](https://goerli.etherscan.io/address/0x5fc523e13fbac2140f056ad7a96de2cc0c4cc63a) it would be nicer to have it called SVT (and to not be confused). 

I see changes necessary in `tokens.py` and `raiden-wizard/resources/conf/goerli.toml`

**Comment by manuelwedler** [comment]
Yes you are right, that would be much nicer. I think it could be easy. I will try it.

**Comment by fredo** [comment]
Thanks a lot!

**Pull request merged**
